name: Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.ts"
      - "**.js"
      - "**.json"
      - "yarn.lock"

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      
      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install
      
      - name: Run benchmarks
        run: yarn bench
